/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/JQ837y9aE6J
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Link } from "react-router-dom"
import { CardContent, CardFooter, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function Authtest() {
  return (
    (<main
      className="flex min-h-screen items-center justify-center bg-gray-950 px-4 py-12 dark:bg-gray-950">
      <div className="w-full max-w-md space-y-4">
        <div className="text-center">
          <h1 className="text-3xl font-bold text-gray-50">Welcome Back</h1>
          <p className="text-gray-400">Sign in to your account to continue.</p>
        </div>
        <Card className="bg-gray-800 border border-gray-700">
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label className="text-gray-400" htmlFor="username">
                Username
              </Label>
              <Input
                className="bg-gray-700 border-gray-600 text-gray-50 placeholder:text-gray-400 focus:border-gray-500 focus:ring-gray-500"
                id="username"
                placeholder="Enter your username"
                required
                type="text" />
            </div>
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <Label className="text-gray-400" htmlFor="password">
                  Password
                </Label>
                <Link className="text-sm text-gray-400 underline hover:text-gray-50" href="#">
                  Forgot password?
                </Link>
              </div>
              <Input
                className="bg-gray-700 border-gray-600 text-gray-50 placeholder:text-gray-400 focus:border-gray-500 focus:ring-gray-500"
                id="password"
                placeholder="Enter your password"
                required
                type="password" />
            </div>
          </CardContent>
          <CardFooter>
            <Button
              className="w-full bg-gray-700 text-gray-50 hover:bg-gray-600 focus:ring-gray-600"
              type="submit">
              Sign in
            </Button>
          </CardFooter>
        </Card>
        <div className="text-center text-sm text-gray-400">
          Don't have an account?
          <Link
            className="font-medium text-gray-50 underline hover:text-gray-300"
            href="#">
            Register
          </Link>
        </div>
      </div>
    </main>)
  );
}
